# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/node:8.1.4

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    # run tests!
    - run: yarn test

    - setup_remote_docker

    - run: |
        docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD

    - run:
        name: Build Docker Image
        command: docker build -t rev42/dockerci:$CIRCLE_SHA1 .

    - run:
        name: Push to DockerHub
        command: |
          docker push rev42/dockerci:$CIRCLE_SHA1
  deploy:
      machine:
        enabled: true
      steps:
        - run:
            name: Deploy Over SSH
            command: |
              ssh $SSH_USER@$SSH_HOST "docker stop dockerci"
              ssh $SSH_USER@$SSH_HOST "docker rm dockerci"
              ssh $SSH_USER@$SSH_HOST "docker pull rev42/dockerci"
              ssh $SSH_USER@$SSH_HOST "docker run -d --name dockerci -p 80:8080 rev42/dockerci:latest"

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master